-- okay so we are making a big fella.
-- literally all he needs to do is move around as of right now
-- we will figure out how on gods green EARTH to give this man a gun
-- dev notes will be present for myself, DO NOT PUT THOSE IN THE PICTURES FOR THE DEVELOPMENT LOG!!!!!!!!!


math.randomseed (100000000000000 * (socket.gettime() % 1)) -- use to clear out "bad seed"
for i=1,20 do
	math.random()
end


function init(self)
	msg.post(".","acquire_input_focus") -- do know what this means, it will infact not run without this
	self.health = 5
	self.damage = 1
	self.crit = 0
	self.atkspeed = 1
	self.iframes = 0
	self.lastaction = 0
end


function on_input(self, action_id, action)  -- takes in self for oop, action_id is like what it is in game.input_binding 
	if action_id == hash("a") then       -- i dont know what on earth action does
		local pos = go.get_position()
		pos.x = pos.x - 2
		go.set_position(pos)
	elseif action_id == hash("d") then
		local pos = go.get_position()
		pos.x = pos.x + 2
		go.set_position(pos)
	elseif action_id == hash("w") then
		local pos = go.get_position()
		pos.y = pos.y + 2
		go.set_position(pos)
	elseif action_id == hash("s") then
		local pos = go.get_position()
		pos.y = pos.y - 2
		go.set_position(pos)
	elseif action_id == hash("attack") and action.pressed then
		local now = socket.gettime()
		if now > self.lastaction + 0.75 then 
			local pos = go.get_position()
			pos.y = pos.y - 20
			local component = "#attack_factory"
			factory.create(component,pos)
			self.lastaction = now
		end
	elseif action_id == hash("m1") and action.pressed then -- oops 16/9 dont do that again
		local now = socket.gettime()
		if now > self.lastaction + 0.75 then 
			local pos = go.get_position()
			local target_pos = vmath.vector3(action.x, action.y, 0)
			local duration = 0.75
			local component = "#attack_factory"
			ranged = factory.create(component,pos)
			go.animate(ranged, "position", go.PLAYBACK_ONCE_FORWARD, target_pos, go.EASING_LINEAR, duration, 0)
		end
			
		
	end	
end


function on_message(self, message_id, message, sender)
	-- Handle collision
	if message_id == hash("contact_point_response") and message.other_group == hash("walls") then
		local newpos = go.get_position() + message.normal * message.distance
		go.set_position(newpos)
	
	elseif message_id == hash("contact_point_response") and self.iframes <= 0 and message.other_group == hash("enemy") then
		self.health = self.health - 1
		print("Player health = "..self.health)
		self.iframes = 1
		if self.health == 0 then
			go.delete("/player") -- screw death amirite -- debug mode bc im lazy
		end
	elseif message_id == hash("trigger_event") then
		print("We are so back")
	
	elseif message_id == hash("item_collected") then
		local powerup = math.random(1,4)
		if powerup == 1 then
			self.health = self.health + 2
			print("Health")
		elseif powerup == 2 then
			self.damage = self.damage + 1
			print("Damage")
		elseif powerup == 3 then
			self.crit = self.crit + 5
			print("CC")
		elseif powerup == 4 then
			self.atkspeed = self.atkspeed + 1
			print( "ATKSPD")
		else
			print("What the actual fuck has happened here?")
		end	
	
	end
end

function update(self, dt)
	if self.iframes > 0 then
		self.iframes = self.iframes - dt
	end
	
end



-- use factories for ranged
-- use script and trigger collision for melee
-- okay so lets figure out how to make a melee weapon.. -- HANDLED AS OF 11/9