-- item_manager.script
function init(self)
	msg.post(".","acquire_input_focus")
	self.id = go.get_id()
	print(self.id)
end

--function spawn_item()
--	local position = vmath.vector3(math.random(0, 800), math.random(0, 600), 0)
--	factory.create("#item_factory", position)
--end

function on_message(self, message_id, message) 
	if message_id == hash("go") then
		local start_pos = vmath.vector3(0, 300, 0)	
		local end_pos = vmath.vector3(480,0,0)
		local chineseworker = vmath.lerp(self.t, start_pos, end_pos)
		local component = "/item#sheinfactory"
		factory.create(component, chineseworker)
	end
end