-- item.script
function init(self)
	msg.post(".","acquire_input_focus")
	self.powerup = math.random (4)
end

function update(self, dt)
	if go.exists("/player") == true then
-- detect collision with the player
		local player_pos = go.get_position("/player")
		local item_pos = go.get_position()

		local distance = vmath.length(player_pos - item_pos)
		if distance < 16 then  -- assuming a 16px threshold for collection
			msg.post("/player", "item_collected")
			go.delete()  -- remove the item once collected
		end
	end
end	