function init(self)
	msg.post(".", "acquire_input_focus")
	self.player_id = go.get_id("/player")
	self.frames = 0
	self.spawn = 0
	-- local Attackspeed = go.get("/player", "self.atkspeed")
	self.atkspeed = 60
end

function on_input(self, action_id, action)
	if action_id == hash("attack") then
		self.spawn = 1
		
	end
end

function update(self, dt)
	self.atkspeed = self.atkspeed - dt
	if self.spawn == 1 and self.atkspeed <= 0 then
		if go.exists("/player") then
			self.spawn = 0
			self.atkspeed = 1
		end
	end
end
				
		
		
			
		