-- unless if you feel like committing to this black magic, although you do know how this works
-- dont link this to anything please

function init(self)
	msg.post(".", "acquire_input_focus") 
	self.speed = 350
end

function on_input(self, action_id, action)
	if action_id == hash("m1") then 
		local current_pos = go.get_position() 
		local target_pos = vmath.vector3(action.x, action.y, 0) 
		local distance = vmath.length(target_pos - current_pos) 
		local duration = distance / self.speed 
		go.animate(".", "position", go.PLAYBACK_ONCE_FORWARD, target_pos, go.EASING_LINEAR, duration, 0)
	end
end

function on_message(self, message_id, message, sender)
	-- Handle collision
	if message_id == hash("contact_point_response") then
		local newpos = go.get_position() + message.normal * message.distance
		go.set_position(newpos)
	end
end