function init(self)
	msg.post(".","acquire_input_focus") 
end

function on_input(self, action_id, action)   
	if action_id == hash("a") then       
		local pos = go.get_position()
		pos.x = pos.x - 10
		go.set_position(pos)
	elseif action_id == hash("d") then
		local pos = go.get_position()
		pos.x = pos.x + 10
		go.set_position(pos)
	elseif action_id == hash("w") then
		local pos = go.get_position()
		pos.y = pos.y + 10
		go.set_position(pos)
	elseif action_id == hash("s") then
		local pos = go.get_position()
		pos.y = pos.y - 10
		go.set_position(pos)
	end	
end

-- a second, bigger fella, maybe even a "fella2"