function init(self)
	-- make man
	msg.post(".","acquire_input_focus")
end

function final(self)
	-- kill man
end

function update(self, dt)
	-- update man per function
end

function fixed_update(self, dt)
	-- This function is called if 'Fixed Update Frequency' is enabled in the Engine section of game.project
	-- Can be coupled with fixed updates of the physics simulation if 'Use Fixed Timestep' is enabled in
	-- Physics section of game.project
	-- YUCK
end

function on_message(self, message_id, message, sender)
	-- do something on a new message
end

function on_input(self, action_id, action)
	-- user press button, man go
end

function on_reload(self)
	-- hot reload bc defold funny
end

-- ok so what am i actually doing
-- rooms
-- better enemies
-- items -- DO FIRST
